services:
  registry:
    image: registry:2            # シンプル HTTP レジストリ
    restart: always              # 自動再起動
    environment:
      REGISTRY_STORAGE: filesystem
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    ports:
      - "5000:5000"              # ホストの 5000→コンテナの 5000
    volumes:
      - ./data:/var/lib/registry # データ永続化