services:
  registry:
    image: registry:latest       # シンプル HTTP レジストリ (latest タグ)
    restart: always              # 自動再起動
    environment:
      REGISTRY_STORAGE: filesystem
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: "*"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: "GET, OPTIONS"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: "Authorization, Content-Type"
    ports:
      - "5000:5000"              # ホストの 5000→コンテナの 5000
    volumes:
      - ./data:/var/lib/registry # データ永続化

  ui:
    image: nginx:stable-alpine   # シンプルUI用
    restart: always
    ports:
      - "8080:80"               # ホストの8080→コンテナの80
    volumes:
      - ./ui:/usr/share/nginx/html:ro
    depends_on:
      - registry